apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-server
  labels:
    app: company-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-server
  template:
    metadata:
      labels:
        app: company-server
    spec:
      containers:
      - name: company-server
        image: companyimg:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: company-server-svc
spec:
  selector:
    app: company-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
