apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-dumper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-dumper
  template:
    metadata:
      labels:
        app: json-dumper
    spec:
      containers:
      - name: json-dumper
        image: jsondumperimg:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: json-dumper-svc
spec:
  type: LoadBalancer
  selector:
    app: json-dumper
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080